### ISSUE TITLE
Switch from Gotham to Actix

### ISSUE THREAD

**Issue by mitchtbaum** [hntd187/Toshi#3]
Since [actix-web has removed all unsound use of unsafe in its codebase](https://www.reddit.com/r/rust/comments/8wlkbe/actixweb_has_removed_all_unsound_use_of_unsafe_in/), when do you [plan to switch to acitx-web as mentioned on reddit](https://www.reddit.com/r/rust/comments/925ixh/toshi_a_full_text_search_engine_based_on_tantivy/e34fq9d/)?

**Comment by hntd187** [comment]
The main attractiveness of switching to actix was I was hoping it had a remote actor system like what akka has in it's akka-remote, but I think remote is still a work in progress for them so I'm still somewhat in a place where I can't combine the http layer of this and the remoting layer. It is also is way more work than I originally thought (I dunno why I thought it would be easy) but it doesn't seem to have any real immediate benefit when there are other basic functionality aspects that still need to be implemented.
