### ISSUE TITLE
Feature request: versioning and github releases

### ISSUE THREAD

**Issue by h7x4** [hntd187/toshi#982]
Hello! Thank you for making a great project.

I'm wondering if you'd be willing to start versioning the project? It doesn't need to be a very formal thing with big changelogs and so on, just every now and then when things grow stable, could you create a git tag + release? It would make it easier for downstream distributions and package repositories to package and distribute your software.

**Comment by hntd187** [comment]
I don't plan to do this because I don't want to give people the impression this is ready for such distribution or production usage.

**Comment by h7x4** [comment]
That's okay. I'll be closing this then.
